# syntax=docker/dockerfile:1
FROM python:3.10-alpine

WORKDIR /app
COPY ./flask_app.py /app/
COPY ./requirements.txt /app/

# Install python dependencies
RUN pip install -r requirements.txt

# Make deploy script executable
RUN chmod +x flask_app.py

# Expose port 5000 for Flask app
EXPOSE 5000

# This line runs the deploy script upon running the container
CMD ["python", "flask_app.py"]