# syntax=docker/dockerfile:1
FROM python:3.10-alpine

WORKDIR /app
COPY ./deploy.py /app/
COPY ./lambdas /app/lambdas/
COPY ./config /app/config/
COPY ./requirements.txt /app/

# Remove all zip files from the lambdas folder
WORKDIR /app/lambdas
RUN find . -type f -name "*.zip" -exec rm {} \;
WORKDIR /app

# # Install packages if needed
# RUN apk add zip
# RUN apk add curl
# RUN apk add jq

# Install python dependencies
RUN pip install -r requirements.txt

# Make deploy script executable
RUN chmod +x deploy.py

# This line runs the deploy script upon running the container
CMD ["python", "deploy.py"]