# This dockerfile starts an identical container as template-microservice, but runs indefinitely. Can be used to manually run the test/test_XXX.py scripts
# This duplication is needed to ensure the boto3 clients can  use the deployed localstack instances

# syntax=docker/dockerfile:1
FROM python:3.10-alpine

WORKDIR /app
COPY ./backend/template-microservice/deploy.py /app/
COPY ./backend/template-microservice/deploy_utils.py /app/
COPY ./backend/template-microservice/lambdas /app/lambdas/
COPY ./backend/template-microservice/config /app/config/
COPY ./backend/template-microservice/requirements.txt /app/

# Remove all zip files from the lambdas folder
WORKDIR /app/lambdas
RUN find . -type f -name "*.zip" -exec rm {} \;
WORKDIR /app

# Install packages if needed
RUN apk update && apk upgrade
# RUN apk add zip
RUN apk add curl
# RUN apk add jq

# Add python compilers to install wheels, don't ask why, but it works
RUN apk add python3-dev
RUN apk add gcc
RUN apk add libc-dev
RUN apk add libffi-dev

# Install python dependencies
RUN pip install -r requirements.txt

# Make deploy script executable
RUN chmod +x deploy.py

# Keep running forever
ENTRYPOINT ["tail", "-f", "/dev/null"]