# This dockerfile starts an identical container as template-microservice, but runs indefinitely. Can be used to manually run the test/test_XXX.py scripts
# This duplication is needed to ensure the boto3 clients can  use the deployed localstack instances

# syntax=docker/dockerfile:1
FROM python:3.10-alpine

WORKDIR /app

COPY ./product-microservice/lambdas /app/lambdas/
COPY ./product-microservice/config /app/config/
COPY ./product-microservice/test /app/test/
COPY ./product-microservice/requirements.txt /app/

# Copy from the template
COPY ./template-microservice/deploy_utils.py /app/
COPY ./template-microservice/deploy.py /app/

# Remove all zip files from the lambdas folder
WORKDIR /app/lambdas
RUN find . -type f -name "*.zip" -exec rm {} \;
WORKDIR /app

# # Install packages if needed
#RUN apk update && apk upgrade
RUN apk update
# RUN apk add zip
RUN apk add curl
# RUN apk add jq

# Install python dependencies
RUN pip install -r requirements.txt

# Make deploy script executable
RUN chmod +x deploy.py

# Keep running forever
ENTRYPOINT ["tail", "-f", "/dev/null"]