# syntax=docker/dockerfile:1
FROM python:3.10-alpine

WORKDIR /app

COPY ./product-microservice/lambdas /app/lambdas/
COPY ./product-microservice/config /app/config/
COPY ./product-microservice/requirements.txt /app/

# Copy from the template
COPY ./template-microservice/deploy_utils.py /app/
COPY ./template-microservice/deploy.py /app/
# Copy the OPTIONS default handler from the template
#RUN mkdir lambdas/options_default
COPY ./template-microservice/lambdas/options_default/handler.py /app/lambdas/options_default/


# Remove all zip files from the lambdas folder
WORKDIR /app/lambdas
RUN find . -type f -name "*.zip" -exec rm {} \;
WORKDIR /app

# # Install packages if needed
# RUN apk add zip
# RUN apk add curl
# RUN apk add jq

# Install python dependencies
RUN pip install -r requirements.txt

# Make deploy script executable
RUN chmod +x deploy.py

# This line runs the deploy script upon running the container
CMD ["python", "deploy.py"]