# Generated by Django 4.2.7 on 2024-03-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product', models.CharField(max_length=200)),
                ('highlighted', models.BooleanField(default=False)),
                ('image', models.URLField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('formatted_text', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
            ],
        ),
    ]
