# syntax=docker/dockerfile:1
FROM python:3.10-alpine

WORKDIR /app
COPY ./template-microservice/deploy.py /app/
COPY ./template-microservice/deploy_utils.py /app/
COPY ./template-microservice/lambdas /app/lambdas/
COPY ./template-microservice/config /app/config/
COPY ./template-microservice/requirements.txt /app/

# Remove all zip files from the lambdas folder
WORKDIR /app/lambdas
RUN find . -type f -name "*.zip" -exec rm {} \;
WORKDIR /app

# # Install packages if needed
# RUN apk add zip
# RUN apk add curl
# RUN apk add jq

# Add python compilers to install wheels, don't ask why, but it works
RUN apk add python3-dev
RUN apk add gcc
RUN apk add libc-dev
RUN apk add libffi-dev

# Install python dependencies
RUN pip install -r requirements.txt

# Make deploy script executable
RUN chmod +x deploy.py

# This line runs the deploy script upon running the container
CMD ["python", "deploy.py"]