name: Python pytest coverage

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
        
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      working-directory: PYTHON/py
  
    - name: Run tests with coverage
      run: |
        coverage run -m pytest -s
        coverage xml -o .qodana/code-coverage/coverage.xml
      working-directory: PYTHON/py

    - name: Archive coverage data
      uses: actions/upload-artifact@v2
      with:
        name: py-coverage-data
        path: PYTHON/py/.qodana/code-coverage

    - name: Qodana Scan
      uses: JetBrains/qodana-action@main
      env:
        QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_PYTHON }}
      with:
        args: "-i,PYTHON/py,--linter,jetbrains/qodana-python:2023.3-eap"
        pr-mode: false